force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductInfo.cls
public with sharing class ProductInfo {
     @AuraEnabled
    public static List<Product2> getProductDetails(Id caseId){
        Id ids = OpenissuesCtrlr.getConId(caseId);
        Contact con =null;
        if(ids!=null){
            con = [SELECT Id,Product__c,Home_Country__c FROM Contact Where Id =:ids];
        }
       	if(con!=null && String.isNotBlank(con.Product__c) && String.isNotBlank(con.Home_Country__c) )
            return [SELECT Id,Name,	Home_Country__c,Cost_per_Calendar_Month__c,Card_Replacement_Cost__c,ATM_Fee_in_other_currencies__c FROM Product2 WHERE Name = :con.Product__c AND Home_Country__c=:con.Home_Country__c];
	    return null;    
    }

}