force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpenissuesCtrlr.cls
public with sharing class OpenissuesCtrlr {
    @AuraEnabled
    public static Contact getContactDetails(Id caseId){
        Id ids = OpenissuesCtrlr.getConId(caseId);
       	if(ids!=null)
            return [SELECT Id,Product__c,Home_Country__c FROM Contact Where Id =:ids];
	    return null;    
    }
    @AuraEnabled
    public Static Id getConId(Id caseId){
        return [SELECT contact.Id from Case WHERE Id = : caseId LIMIT 1].contactId; 
    }
  

}