force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendSurveysBatchTest.cls
@isTest
private class SendSurveysBatchTest {

    @isTest static void testBatch() {
        Account testAccount = new Account(Name = 'test');
        insert testAccount;
        Contact testContact = new Contact(AccountId = testAccount.Id,
            FirstName = 'firstName1',
            LastName = 'lastName1',
            Email = 'email1@email.test',
            Language__c = 'EN',
            Survey_Date__c = Date.today() - 1
        );
        Contact testContact2 = new Contact(AccountId = testAccount.Id,
            FirstName = 'firstName2',
            LastName = 'lastName2',
            Email = 'email1@email.test2',
            Language__c = 'EN',
            Survey_Date__c = Date.today() - 1
        );
        INSERT new List<Contact> {testContact,testContact2};
        Test.startTest();
        Database.executeBatch(new SendSurveyBatch(), SendSurveyBatch.EMAILS_PER_BATCH);
        Test.stopTest();
        for(Contact con:[SELECT Survey_Date__c FROM Contact LIMIT 2]){
            System.assertEquals(null, con.Survey_Date__c);
        }
    }

}